---
all:
  children:
    spine:
      hosts:
        spine01:
          ansible_host: 192.168.1.10
          spine_id: 1
          loopback0: 10.255.1.1/32
          spine_interfaces:
            - interface: 10GE1/0/1
              description: "Link to leaf01"
              ip: 10.1.1.1/30
            - interface: 10GE1/0/2
              description: "Link to leaf02"
              ip: 10.1.1.5/30
        spine02:
          ansible_host: 192.168.1.11
          spine_id: 2
          loopback0: 10.255.1.2/32
          spine_interfaces:
            - interface: 10GE1/0/1
              description: "Link to leaf01"
              ip: 10.1.1.9/30
            - interface: 10GE1/0/2
              description: "Link to leaf02"
              ip: 10.1.1.13/30
    
    leaf:
      hosts:
        leaf01:
          ansible_host: 192.168.1.20
          leaf_id: 1
          loopback0: 10.255.2.1/32
          vtep_loopback: 10.255.3.1/32
          leaf_interfaces:
            - interface: 10GE1/0/1
              description: "Link to spine01"
              ip: 10.1.1.2/30
            - interface: 10GE1/0/2
              description: "Link to spine02"
              ip: 10.1.1.10/30
            - interface: 10GE1/0/48
              description: "Server Access"
              mode: access
              vlan: 100
        leaf02:
          ansible_host: 192.168.1.21
          leaf_id: 2
          loopback0: 10.255.2.2/32
          vtep_loopback: 10.255.3.2/32
          leaf_interfaces:
            - interface: 10GE1/0/1
              description: "Link to spine01"
              ip: 10.1.1.6/30
            - interface: 10GE1/0/2
              description: "Link to spine02"
              ip: 10.1.1.14/30
            - interface: 10GE1/0/48
              description: "Server Access"
              mode: access
              vlan: 200
